// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFF61WGpdtbBIMxIlTDl17QiUUdzSalL0',
    appId: '1:275767774324:web:2423fec7bd2d1aee491521',
    messagingSenderId: '275767774324',
    projectId: 'pi-urbanai',
    authDomain: 'pi-urbanai.firebaseapp.com',
    storageBucket: 'pi-urbanai.firebasestorage.app',
    measurementId: 'G-DTTJ05TCRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyqbEHRem8xrC4mzaz4y2nIFjd7JwGVIA',
    appId: '1:275767774324:android:81f0b5b14ac2633a491521',
    messagingSenderId: '275767774324',
    projectId: 'pi-urbanai',
    storageBucket: 'pi-urbanai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArPs_iGqKrnPzNWcMI_PiuW6Ga1A8emYI',
    appId: '1:275767774324:ios:dbb9c0c69a38178a491521',
    messagingSenderId: '275767774324',
    projectId: 'pi-urbanai',
    storageBucket: 'pi-urbanai.firebasestorage.app',
    iosClientId: '275767774324-cekrk5f060vffsl4mlldpeosfdiu0oqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.urbanai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFF61WGpdtbBIMxIlTDl17QiUUdzSalL0',
    appId: '1:275767774324:web:e1b15d3cb956b86e491521',
    messagingSenderId: '275767774324',
    projectId: 'pi-urbanai',
    authDomain: 'pi-urbanai.firebaseapp.com',
    storageBucket: 'pi-urbanai.firebasestorage.app',
    measurementId: 'G-PD7HPVZQ7B',
  );

}